### ISSUE TITLE
[Hunter][Pet][Item][Spell] Hunter T7 2/5 set bonus doesn't work

### ISSUE THREAD

**Issue by Nuy** [Stormforge-gg/Bugtracker-Fordring#1216]
[//]: # (Enclose links to things related to the bug using http://wowhead.com)
[//]: # (Write your tickets according to the format:)
[//]: # ([Quest][Zone] A Vision of the Past)
[//]: # ([NPC] Thoralius the Wise)
[//]: # ([Spell][Class] Frostfire Bolt)
[//]: # ([Talent][Class] Brain Freeze)
[//]: # ([Glyph][Class] Glyph of Frostfire Bolt)
[//]: # ([Npc][Drop] Thoralius the Wise)
[//]: # ([Web] Armory doesnt work)

**Description**: Right now this set bonus doesn't work at all (doesn't increase pet damage by 5%). 

**Current behaviour**: Set bonus doesn't work at all (doesn't increase pet damage by 5%).

**Expected behaviour**: Should increase ALL of hunter's pet damage by 5%.

https://wotlk.evowow.com/?spell=60143
https://www.wowhead.com/spell=60143/item-naxxramas-t7-hunter-2p-set-bonus

**Revision**: 1487

**Comment by Wolffenstein** [comment]
Fixed in rev 1498.

**Comment by Nuy** [comment]
> Fixed in rev 1498.

Still doesn't seem to work in rev 1504. If anything pet actually seems to deal much less damage when 2/5 set bonus is there (really weird) despite pet stats staying pretty much exactly the same when I swap chests. I tested it on a level 80 dummy and was hit capped with both chests.
