### ISSUE TITLE
[Saragosa's End][Borean Tundra] Missing teleport dialog option.

### ISSUE THREAD

**Issue by FX-SF** [Stormforge-gg/Bugtracker-Fordring#1241]
**Description**:

1.  In the quest [Saragosa's End](https://www.wowhead.com/quest=11957/saragosas-end#comments), you can use [Augmented Arcane Prison ](https://www.wowhead.com/item=35671/augmented-arcane-prison) to summon [Keristrasza ](https://www.wowhead.com/npc=26206/keristrasza).
2.  She will teleport you to a very high place.
3.  There you will defear [Saragosa](https://www.wowhead.com/npc=26232/saragosa) and loot [Saragosa's Corpse](https://www.wowhead.com/item=35709/saragosas-corpse). 

**Current behaviour**: 

1. [Keristrasza](https://www.wowhead.com/npc=26206/keristrasza) never offers player the teleport dialog option. _(see expected behavior)_. 
2. A player without a flying mount will often jump to their deaths and corpse run.

**Expected behaviour**: 

1. Upon obtaining [Saragosa's Corpse](https://www.wowhead.com/item=35709/saragosas-corpse), [Keristrasza](https://www.wowhead.com/npc=26206/keristrasza) should provide the player with a dialog option: `"_Keristrasa_, I am finished here. Please return me to the Transitus Shield."
2.  Although unintended, there should be a typo in the dialog: _Keristrasa_. 
3. When selecting this dialolg option, Keristrasza should teleport a player back to the Transitus Shield.

**Revision**: 1487

Evidence: 2021 Video (probably private server)
https://youtu.be/sg77ndAC-_o?t=38

**Comment by Tereneckla** [comment]
Fixed soon™

**Comment by fondlez** [comment]
Why was this closed? This bug still exists. Re-using [Augmented Arcane Prison] will not summon a version of Keristrasza that offers a teleport down option. Players still left stranded at the top of a mile high platform. Death is the only option without a Northrend flying mount.
